[newsstand UI] 리뷰 요청합니다. :)
code-squad/masteringjs_newsui pull request #3
Opened 2018-10-05 13:06 UTC by hyeyoon

newsstand UI 미션 리뷰 요청합니다.

2018-10-05 13:06 UTC, hyeyoon commented
[newsstand UI 프로젝트 구현 링크](http://hyeyoonjung.com/masteringjs_newsui/main.html)

2018-10-06 00:37 UTC, nigayo commented
오! 데모까지~
끝까지 네비게이션이 이동하면 다시 좌/우버튼이 동작하지 않는 문제가 있지만~ 잘 했어요. ㅎ

2018-10-06 00:49 UTC, crongro requested changes
잘 구현했어요! 👍 

리뷰남겨드립니다. 수정해보세요~

2018-10-06 00:49 UTC, nigayo commented on js/main.js
> +import { fnNewsCompanyList } from '../templates/company.js'
잘 했어요.

2018-10-06 00:49 UTC, nigayo commented on js/main.js
> +    news.init(fnNewsListTemplate, fnNewsCompanyList);
init에서 인자를 받는게 혹시 늘어나면, 
아래처럼 객체를 사용해서 이름을 부여해서 넘기는 것도 좋을 거에요.
news.init({templates : []});

2018-10-06 00:49 UTC, nigayo commented on js/newsSection.js
> +    this.activeNewsCompanyIndex = 0;
이런 상태정보를 가지고 있으면, 상태관리를 잘 해야 합니다.
DOM과 sync를 해줘야 하는 것이라 자칫 틀리면 버그가 생기는거죠.
그래서 DOM에 active정보가 있다면 그걸 매번 직접 찾는 것도 방법이고요.

2018-10-06 00:49 UTC, nigayo commented on js/newsSection.js
> +  setNewsList() {
잘 했네요~ 간결하고 좋아요.
set 이라는 이름은 프로그래밍에서 환경설정과 같은 행동을 할때 좀더 많이 쓰는 거 같아요.
view쪽 작업이니까, render로 시작해도 좋을 듯 해요.

2018-10-06 00:49 UTC, nigayo commented on js/newsSection.js
> +      newsCompany.innerHTML = fnNewsCompanyList.bind(this)(news);
bind => call 이나 apply !

2018-10-06 00:49 UTC, nigayo commented on js/newsSection.js
> +    newsNavigation.addEventListener('click', (evt) => this.delegateEventToChild(evt));
잘했어요. 

다른방법으로는 이렇게 해도 될듯.  this문제가 있으면 bind쓰고요.
newsNavigation.addEventListener('click', this.delegateEventToChild.bind(this));

2018-10-06 00:49 UTC, nigayo commented on js/newsSection.js
> +    activeCompany.classList.remove("active");
잘했어요.

2018-10-06 00:49 UTC, nigayo commented on js/newsSection.js
> +      const newsCompany = document.createElement('li');
li를 반복하면서 계속 innerHTML로 넣으면 DOM조작이 빈번하게 자주 일어나는데요.
(물론 이부분에서 js engine이 최적화를 해줄 수도 있어요)
이것보다는 li를 모두 html문자열로 묶어서 한번만 innerHTML을 사용해서 추가하는게 좋아요.

그 과정에서 map.join을 쓰던지, reduce를 쓰던지~ 선택하고요.

2018-10-16 14:26 UTC, hyeyoon commented
피드백 반영해서 코드 수정했습니다. :)

2018-10-18 08:02 UTC, crongro approved these changes
이정도 수준으로만 구현해도 참 잘 한 거라 생각해요. ^^

앞으로 oop관점으로 좀더 고민하면, 
객체가 더 많아졌을때, 어떻게 역할을 정의하고 서로 호출하면 좋을까? 이런 고민을 많이 해보시면 좋을 거에요.

2018-10-18 08:02 UTC, crongro commented on js/main.js
> +  news.init({template: [fnNewsListTemplate, fnNewsCompanyList]});
네 key값이 있어서 무엇인지 알기 쉽죠.

2018-10-18 08:02 UTC, crongro commented on js/newsSection.js
> +    const [fnNewsListTemplate, fnNewsCompanyList] = template;
👍

2018-10-18 08:02 UTC, crongro commented on js/newsSection.js
> +    const newsCompanyEl = this.newsCompanyList.map((news, index) => {
네 templating 처리는 map.join을 가장 많이 쓰더라고요.
reduce를 써도 사실 좋고요~

2018-10-18 08:02 UTC, crongro commented on js/newsSection.js
> +      if (item.classList.contains('active')) {
반복문 안에 조건문이 있으면 
대부분 filter함수를 먼저 사용할 수 있는지 검토해보세요.

2018-10-18 08:02 UTC, merged